In [2]:
import pandas as pd

In [22]:
data = pd.read_csv("loan_approval_dataset.csv")

In [23]:
data

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4264,4265,5,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4265,4266,0,Not Graduate,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4266,4267,2,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4267,4268,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,4269,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [24]:
data = data.drop(columns=["loan_id"])

In [25]:
data.columns = data.columns.str.strip()

In [26]:
print(data.columns.tolist())

['no_of_dependents', 'education', 'self_employed', 'income_annum', 'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value', 'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value', 'loan_status']

In [27]:
data = data.rename(columns={"loan_status": "loan_approved"})

data["loan_approved"] = (
    data["loan_approved"]
    .astype(str)
    .str.strip()
    .map({
        "Approved": True,
        "Rejected": False
    })
)

In [29]:
data = data.rename(columns={"education": "graduated"})

data["graduated"] = (
    data["graduated"]
    .astype(str)
    .str.strip()
    .map({
        "Graduate": True,
        "Not Graduate": False
    })
)

In [32]:
data["self_employed"] = (
    data["self_employed"]
    .astype(str)
    .str.strip()
    .map({
        "Yes": True,
        "No": False
    })
)

In [34]:
data

,no_of_dependents,graduated,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_approved
0,2,True,False,9600000,29900000,12,778,2400000,17600000,22700000,8000000,True
1,0,False,True,4100000,12200000,8,417,2700000,2200000,8800000,3300000,False
2,3,True,False,9100000,29700000,20,506,7100000,4500000,33300000,12800000,False
3,3,True,False,8200000,30700000,8,467,18200000,3300000,23300000,7900000,False
4,5,False,True,9800000,24200000,20,382,12400000,8200000,29400000,5000000,False
...,...,...,...,...,...,...,...,...,...,...,...,...
4264,5,True,True,1000000,2300000,12,317,2800000,500000,3300000,800000,False
4265,0,False,True,3300000,11300000,20,559,4200000,2900000,11000000,1900000,True
4266,2,False,False,6500000,23900000,18,457,1200000,12400000,18100000,7300000,False
4267,1,False,False,4100000,12800000,8,780,8200000,700000,14100000,5800000,True
4268,1,True,False,9200000,29700000,10,607,17800000,11800000,35700000,12000000,True

In [37]:
print(data.isna().sum())

no_of_dependents            0
graduated                   0
self_employed               0
income_annum                0
loan_amount                 0
loan_term                   0
cibil_score                 0
residential_assets_value    0
commercial_assets_value     0
luxury_assets_value         0
bank_asset_value            0
loan_approved               0
dtype: int64

In [38]:
data.to_csv("cleaned_loan_data.csv", index=False)